version: '3.7'
services:
  odoo:
    container_name: ${ODOO_HOST}
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
      - "${LONGPOLLING_PORT}:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
    entrypoint: "odoo -c /etc/odoo/odoo.conf --dev all -u rh_estevez"

  db:
    container_name: ${DB_HOST}
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSW}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
volumes:
  db-data:
  odoo-data:


